login.url=http://0.0.0.0:8001/auth/login
register.url=http://0.0.0.0:8002/register
auth.me.url=http://0.0.0.0:8001/auth/me
paciente.url=http://0.0.0.0:8003/paciente
estilo_vida.url=http://0.0.0.0:8004/estilo_vida
predict.url=http://0.0.0.0:8008/predict_diabetes